### PR TITLE
Fix permit

### PR DESCRIPTION
**Pull request by MohammadPCh**
- #3420

## Summary by CodeRabbit

- **New Features**
  - Added toggle switch for permitting or approving mode in staking modals.
  - Introduced permit functionality, allowing users to provide permit signatures for staking tokens.

- **Bug Fixes**
  - Updated subgraph URLs to ensure accurate data fetching.

- **Localization**
  - Added new language labels for permit actions in Catalan, English, and Spanish.

- **Configuration**
  - Updated subgraph addresses for different networks in development and production environments.

### CODE REVIEW

**Review by kkatusic — APPROVED** [review]
Tested on XDAI/FOX and XDAI/HNY pool stake and it is working with permit option turned on.

**Comment by MohammadPCh** [comment]
@kkatusic Thanks, Please **DONT MERGE THIS** since the UI is not complete. can you take this and finalize it?

**Comment by kkatusic** [comment]
> @kkatusic Thanks, Please **DONT MERGE THIS** since the UI is not complete. can you take this and finalize it?

@MohammadPCh I don't understand what is missing, I only tested this, doesn't make any code change? Write what is missing and I will add it, thx

**Comment by kkatusic** [comment]
I tested on Op Sepolia: https://optimism-sepolia.blockscout.com/tx/0x298ba7c241c9dee93c738e5806722290ca62bd9da7540433fff3efaedfb75439?tab=logs

with permit and without permit option it is working.

Enabled also FOX/xDAI otpion on production on Gnosis network:

without permit: https://gnosisscan.io/tx/0x930579bc4497a8a0b310dd3c2d429b7fee308194496935625f1098028ab74383

wit permit:

https://gnosisscan.io/tx/0xfed288e5a9c5890d616bf5be9dbc5d7b8611bd6a801dd8632ef4953ccf54a852

**Review by aminlatifi — DISMISSED** [review]
It's not how it's supposed to be!
The flow is this
1. Sign permit message off-chain by user (no transaction is made)
2. Stake with single transaction using `stakeWithPermit` method.

It's sample transaction uses this method
https://gnosisscan.io/tx/0x801ecb80e130765822518416633174b5e42a1a7ad1d0e75ab4c003a05f3506e4

**Comment by kkatusic** [comment]
> https://gnosisscan.io/tx/0x801ecb80e130765822518416633174b5e42a1a7ad1d0e75ab4c003a05f3506e4

Just for me @aminlatifi , how to find on transaction contract that you provide function `stakeWithPermit`: https://gnosisscan.io/token/0x8a0bee989c591142414ad67fb604539d917889df#code

**Comment by aminlatifi** [comment]
> > https://gnosisscan.io/tx/0x801ecb80e130765822518416633174b5e42a1a7ad1d0e75ab4c003a05f3506e4
> 
> Just for me @aminlatifi , how to find on transaction contract that you provide function `stakeWithPermit`: https://gnosisscan.io/token/0x8a0bee989c591142414ad67fb604539d917889df#code
> 
> thx in advance

The same contract you staked on
https://sepolia-optimism.etherscan.io/address/0xe6836325b13819cf38f030108255a5213491a725#writeProxyContract

**Comment by kkatusic** [comment]
> > > https://gnosisscan.io/tx/0x801ecb80e130765822518416633174b5e42a1a7ad1d0e75ab4c003a05f3506e4
> > 
> > 
> > Just for me @aminlatifi , how to find on transaction contract that you provide function `stakeWithPermit`: https://gnosisscan.io/token/0x8a0bee989c591142414ad67fb604539d917889df#code
> > thx in advance
> 
> The same contract you staked on https://sepolia-optimism.etherscan.io/address/0xe6836325b13819cf38f030108255a5213491a725#writeProxyContract

But that isn't same chain network, maybe this is above my grade :)

**Comment by MohammadPCh** [comment]
@aminlatifi @kkatusic Could you please re-review this? Thanks.

**Review by aminlatifi — APPROVED** [review]
LGTM, thanks @MohammadPCh

**Pull request merged**
