### PR TITLE
FIX: switching networks bug 

### PR DESCRIPTION
**Pull request by mateodaza**
## Summary by CodeRabbit

- **New Features**
	- Improved network switching functionality for enhanced user experience.
	- Added support for dynamically handling network changes based on user actions.

- **Bug Fixes**
	- Refactored control flow for network item clicks to ensure correct network switching.

- **Documentation**
	- Updated interface definitions to reflect new properties and methods for better clarity.

### CODE REVIEW

**Review by MohammadPCh — COMMENTED** [review]
@mateodaza Thanks, Please resolve the conflicts and also the coderabbit suggestions.

**Comment by mateodaza** [comment]
@MohammadPCh ready! sorry your comment skipped my head last week 👍🏼

**Review by MohammadPCh — APPROVED** [review]
Thanks @mateodaza LGTM
Did you read the rabbitCodeAi suggestions? Does it make the code better?

**Comment by mateodaza** [comment]
> Thanks @mateodaza LGTM Did you read the rabbitCodeAi suggestions? Does it make the code better?

yes... they add more verbose
is that ok to skip?

**Comment by MohammadPCh** [comment]
@mateodaza Yeah, Sure ;)

**Pull request merged**
