### PR TITLE
add regex search for banner link in description

### PR DESCRIPTION
**Pull request by divine-comedian**
https://github.com/Giveth/giveth-dapps-v2/issues/3717

Reported by Ashley - looks like the rss feed no longer gives us the thumbnail image directly 

made a regex search for the img src and got the first result in the description field - which is the banner image for the post

### CODE REVIEW

**Review by MohammadPCh — APPROVED** [review]
@divine-comedian LGTM, Thanks.

**Review by MohammadPCh — CHANGES_REQUESTED** [review]
@divine-comedian Oh No!!!! Please don't merge this PR. it affected by the wrong revert problem.

**Comment by MohammadPCh** [comment]
I will rebase this and make it ready.

**Review by MohammadPCh — APPROVED** [review]
OK, It's ready now to merge(the revert problem has been resolved).

**Review by jainkrati — APPROVED** [review]

**Pull request merged**
