### PR TITLE
WIP [Project Verification]: modify project contact form (fields)

### PR DESCRIPTION
**Pull request by Meriem-BM**
Related to #3910
Need to add telegram and WhatsApp icons to @giveth/ui-design-system

### CODE REVIEW

**Comment by Meriem-BM** [comment]
Sure, thanks.

**Comment by RamRamez** [comment]
@Meriem-BM Please link the related issue in the comment and in the Zenhub connect issue section (install Zenhub extension first).

image

**Review by RamRamez — CHANGES_REQUESTED** [review]
Awesome, thanks @Meriem-BM. Please fix Whats app placeholder and those two icons. Then you can merge the PR.
Screenshot 2024-04-17 at 4 03 00 PM

**Comment by Meriem-BM** [comment]
Thanks @RamRamez I just added those changes

**Review by RamRamez — APPROVED** [review]
Thanks @Meriem-BM

**Review by MohammadPCh — APPROVED** [review]
Thankd @Meriem-BM

**Pull request merged**
