### PR TITLE
Improve detection lang if none is defined 

### LINKED ISSUE #3418: Improve detection of local language on load of website on loading
From #3314

when I visit https://staging.giveth.io/ while connected from spain or mexico the page will load first in english then switch to spanish after a brief moment 

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/8e56eb84-6e1b-48c0-88d8-ea59a876666e

We could improve this feature by not having the first load of the page in english and try to have it detect the country and then load the page in the correct language (spanish).

### PR DESCRIPTION
**Pull request by kkatusic**
Fix #3418 

@divine-comedian, cc @jainkrati, in this issue there aren't any improvement just tracking bug where two env variables missed from the net config file. THx @RamRamez for tracking what is missing.

@divine-comedian I tested with another language, Spanish, please do same end let me know if you didn't define language on Giveth does it load browser default. It should load Spanish language for all countries that use that language.

## Summary by CodeRabbit

- **New Features**
  - Added locale configuration to improve internationalization support.

- **Enhancements**
  - Improved logging of locale settings for better debugging and transparency.

- **Refactor**
  - Updated environment variable usage for locale settings to ensure consistency across the application.

### CODE REVIEW

**Review by RamRamez — CHANGES_REQUESTED** [review]
great! thanks @kkatusic 
Please remove console.log(s) if you don't need them

**Comment by kkatusic** [comment]
> great! thanks @kkatusic Please remove console.log(s) if you don't need them

I like this coderabbitai tool :)

Removed console logs

**Review by RamRamez — APPROVED** [review]
Thanks @kkatusic

**Review by MohammadPCh — APPROVED** [review]
Thanks @kkatusic LGTM

**Pull request merged**
