### PR TITLE
fix: change fetch policy & show error banner after checking round

### PR DESCRIPTION
**Pull request by Meriem-BM**
Related to #4247

## Summary by CodeRabbit

- **New Features**
  - Enhanced data fetching for user scoring by introducing a new parameter to ensure the latest data is retrieved from the network.

- **Bug Fixes**
  - Improved logic flow in the user score refresh process, allowing for better handling of active QF rounds and associated states.

### CODE REVIEW

**Review by MohammadPCh — APPROVED** [review]
Thanks @Meriem-BM

**Comment by maryjaf** [comment]
I've tested on this branch 
https://giveth-dapps-v2-git-hotfix-qfbanner-givethio.vercel.app/?vercelToolbarCode=GC-1_pqCZH2rqDp
and the problem hasn't been fixed
@Meriem-BM 
https://giveth-dapps-v2-git-hotfix-qfbanner-givethio.vercel.app/?vercelToolbarCode=GC-1_pqCZH2rqDp

**Comment by Meriem-BM** [comment]
@maryjaf can you check again pls

**Comment by maryjaf** [comment]
> @maryjaf can you check again pls

Thanks, it has been fixed

**Pull request merged**
