### PR TITLE
Onboard responsive

### PR DESCRIPTION
**Pull request by MohammadPCh**

### CODE REVIEW

**Review by RamRamez — CHANGES_REQUESTED** [review]
Great! Thanks @MohammadPCh 
Just needs some minor improvements for some dimensions.
Please also resolve conflicts.

**Comment by RamRamez** [comment]
e.g.:
image

**Comment by RamRamez** [comment]
or this one:
image

**Comment by RamRamez** [comment]
the onboard steps in mobile view is different from design system:
image

image

**Comment by MohammadPCh** [comment]
> e.g.: image

Fixed. Thank you.

**Comment by MohammadPCh** [comment]
> or this one: image

I cant reproduce this.

**Comment by MohammadPCh** [comment]
> the onboard steps in mobile view is different from design system: image
> 
> image

I talk with Moenic and this is acceptable for this version.

**Comment by aminlatifi** [comment]
The code is OK, just functional test is required.

**Review by aminlatifi — APPROVED** [review]
Thanks @MohammadPCh

**Pull request merged**
