### PR TITLE
Implements useMediaQuery hook

### PR DESCRIPTION
**Pull request by mateodaza**

### CODE REVIEW

**Comment by alireza-sharifpour** [comment]
Thanks @mateodaza for creating the PR,
We are using useMediaQuery in the hook that @RamRamez implemented and it's in categories-develop-branch
and also he cleaned all the code and we are currently using the new hook everywhere.
and also the useDeviceDetect is removed.
So i think we can close this PR.
can you confirm @RamRamez?

**Review by alireza-sharifpour — COMMENTED** [review]
Thanks @mateodaza for the PR,
We are currently using useMediaQuery in the categories-develop-branch,
I think @RamRamez implemented and improved the useDetectDevice hook and we are using this hook everywhere.
So i think we can remove useDeviceDetect.
Am I right? @RamRamez?

**Comment by RamRamez** [comment]
@alireza-sharifpour Yeah, we had three different components for checking user device and I integrate them into one component.
@mateodaza please check `categories-develop-branch` and tell me your ideas about that.

**Comment by mateodaza** [comment]
@RamRamez what's on `categories-develop-branch` is great work - thanks, I'll close this PR but will leave the issue pending for whenever the branch is merged

**Pull request closed without merging**
