### PR TITLE
Add new categories to giveth for polygon qf round

### PR DESCRIPTION
**Pull request by RamRamez**
#3540

### CODE REVIEW

**Comment by RamRamez** [comment]
@laurenluz requested this feature, and it's priority:
"we reaaally need this issue on production by Jan 7"

@MohammadPCh @mohammadranjbarz Please review ASAP.

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @RamRamez  LGTM

**Review by MohammadPCh — APPROVED** [review]
LGTM, Thanks @RamRamez

**Comment by laurenluz** [comment]
having a look at this on staging... we're not going to include "Projects_dragon" right?
image


Also... can we make it so that "other" is below DeSci & Polygon? it's a bit weird that it's not last...
image

@CarlosQ96 @RamRamez @MohammadPCh

**Comment by RamRamez** [comment]
@laurenluz Yes, we won't have the "Dragon" on production :)

In create project page, the main categories are sorted alphabetically. In production we don't have the "other" category, so I think it's ok.
And the "Polygon" round would be before "Technology" in production.

**Pull request merged**
