### PR TITLE
Translate with chtgpt

### PR DESCRIPTION
**Pull request by MohammadPCh**
@laurenluz @mateodaza I used chatgpt to translate our text to es an ca. but I think it's not perfect  :(
I need someone to check the added translations.

### CODE REVIEW

**Comment by mateodaza** [comment]
@sembrestels if you have some spare time you'd be the best to review 😄

**Comment by laurenluz** [comment]
or if Sem can't,  @Zeptimus maybe you could help? :)

**Comment by Zeptimus** [comment]
Yes i can help in the next 24hrs

**Comment by MohammadPCh** [comment]
@Zeptimus please consider that I did it with the Chatgpt's API, and I don't know anything about Spanish or Catalan.
let me know if I can help you to review it easier. maybe I can send english and it's translation for you.

**Comment by Zeptimus** [comment]
Here are the changes we should do (GIV Stream and GIVFarm are missing) https://docs.google.com/document/d/1uXjovr7Pc8MB6r3GO7j3yuIvpajwSMZLxTd1Z_bkIiU/edit

Let me know when those are included, and ill do a final review

**Comment by MohammadPCh** [comment]
I will merge this because it works only for releases and doesn't depend on other functionalities.

**Pull request merged**
