### PR TITLE
Fixes like on project when signing or changing user

### PR DESCRIPTION
**Pull request by mateodaza**

### CODE REVIEW

**Comment by MohammadPCh** [comment]
@mateodaza, Thanks, I think it happens when a user has liked a project and tried to like it again, so we should check why his like doesn't load.

**Comment by maryjaf** [comment]
I checked on this branch and two bugs related to "like"& "share and get rewarded" were happened

**Comment by MohammadPCh** [comment]
@mateodaza I talked with @maryjaf and she tested it and said the problem is still there.

**Comment by mateodaza** [comment]
Thanks @MohammadPCh @maryjaf I think now it should be alright, took me a while 😅

**Comment by mateodaza** [comment]
@maryjaf can you check on this again?

**Comment by maryjaf** [comment]
> @maryjaf can you check on this again?

On STG?

**Comment by mateodaza** [comment]
> > @maryjaf can you check on this again?
> 
> On STG?

It's not merged yet, you can try it out on the preview or wait for @MohammadPCh to merge

**Comment by MohammadPCh** [comment]
@mateodaza Thanks, do we have this problem on the staging? because as I remember we needed this for qf release and It was fixed.
@maryjaf can you test it on the staging? because I think we don't need it and it works properly.

**Comment by maryjaf** [comment]
I checked on stg and I couldn't reproduce it

**Comment by mateodaza** [comment]
> I checked on stg and I couldn't reproduce it

closing this as already solved

**Pull request closed without merging**
