### PR TITLE
Solana donation

### PR DESCRIPTION
**Pull request by aminlatifi**
#3543

### CODE REVIEW

**Comment by MoeNick** [comment]
@alireza-sharifpour @RamRamez Pls review it ASAP

**Review by alireza-sharifpour — APPROVED** [review]
Thanks @aminlatifi

**Comment by RamRamez** [comment]
@aminlatifi I can't donate on devnet using Phantom. I don't know if it's my problem.
image
image
image

**Comment by aminlatifi** [comment]
> @aminlatifi I can't donate on devnet using Phantom. I don't know if it's my problem. image image image

In the setting of phantom configure this
image

**Comment by RamRamez** [comment]
> > @aminlatifi I can't donate on devnet using Phantom. I don't know if it's my problem. image image image
> 
> In the setting of phantom configure this image

Thanks Amin, the problem solved.

**Review by RamRamez — CHANGES_REQUESTED** [review]
image

@aminlatifi I can't see the tx hash here

**Comment by aminlatifi** [comment]
Thanks @RamRamez, you points were addressed via https://github.com/Giveth/giveth-dapps-v2/pull/3536/commits/354ff527888b8c23ca70d1e9eb584b76d1a2e14f

**Review by RamRamez — CHANGES_REQUESTED** [review]
I haven't donated yet but it says "Your transactions have been submitted..."
@aminlatifi can you check it please?
image

**Review by RamRamez — CHANGES_REQUESTED** [review]
We have an issue here, this project (giveth-tour-bridge-the-world) doesn't have any wallet address on Solana, but it accepts Solana token on solana chain:

image

image

as @mohammadranjbarz mentioned [here](https://github.com/Giveth/giveth-dapps-v2/issues/3543#issuecomment-1880023137), backend returns all tokens, so we should filter them on front-end by project wallet addresses, but now I can donate Solana on that project and I get error.

@aminlatifi please check this

**Comment by aminlatifi** [comment]
> I haven't donated yet but it says "Your transactions have been submitted..." @aminlatifi can you check it please? image

It's not related to solana integration, it exists even in production.

**Comment by aminlatifi** [comment]
> We have an issue here, this project (giveth-tour-bridge-the-world) doesn't have any wallet address on Solana, but it accepts Solana token on solana chain:
> 
> image
> 
> image
> 
> as @mohammadranjbarz mentioned [here](https://github.com/Giveth/giveth-dapps-v2/issues/3543#issuecomment-1880023137), backend returns all tokens, so we should filter them on front-end by project wallet addresses, but now I can donate Solana on that project and I get error.
> 
> @aminlatifi please check this

Thanks, this issue must be fixed by https://github.com/Giveth/giveth-dapps-v2/pull/3536/commits/778d35dc5a3250db3f603d7321d32a03cbeabba6

**Review by jainkrati — APPROVED** [review]

**Pull request merged**
