### PR TITLE
Recurring donation setup fix on project creation

### PR DESCRIPTION
**Pull request by mateodaza**
Must point to PRODUCTION backend to work properly

## Summary by CodeRabbit

- **New Features**
	- Introduced a new interface for anchor contract data, enhancing data structure representation.
	- Updated components to support multiple anchor contracts and improved handling of recurring donations.
	- Enhanced project creation and editing logic to incorporate new anchor contract variables.

- **Bug Fixes**
	- Streamlined transaction handling and button logic for anchor contracts.

- **Documentation**
	- Updated type definitions and enumerations to reflect new anchor contract inputs.

### CODE REVIEW

**Review by kkatusic — APPROVED** [review]
This LGTM ;) @mateodaza, but you decide will you do new changes about enabling recurring donation on this PR or on new ;)

**Comment by divine-comedian** [comment]
@mateodaza looks like this PR is still set to use the toggles, I thought we discussed coming back with the buttons.. 

image

**Comment by mateodaza** [comment]
> This LGTM ;) @mateodaza, but you decide will you do new changes about enabling recurring donation on this PR or on new ;)

After discussing w @divine-comedian we gonna do a tiny change and bring back the enable for creation
Will let you know to review again if needed

Thank you lots

**Comment by mateodaza** [comment]
@divine-comedian @kkatusic this is now ready to check again :) - backend is updated

**Pull request merged**
