### PR TITLE
Use react hook form

### PR DESCRIPTION
**Pull request by MohammadPCh**
- #950 
@mateodaza @RamRamez @alireza-sharifpour I'm eager to know your comments about this.

### CODE REVIEW

**Comment by RamRamez** [comment]
Very nice, thanks @MohammadPCh 
I think we can add real-time validation to improve UX.
Also I suggest to merge this branch to verification develop branch to prevent conflicts result from some changes like regex

**Comment by MohammadPCh** [comment]
Thank you @RamRamez 
We can set our revalidation policy in each form. so it's ok I think.
Yeah I implemented it here first then I will merge develop to verification-develop-branch as always ;)

**Review by RamRamez — APPROVED** [review]
Thanks @MohammadPCh

**Review by alireza-sharifpour — APPROVED** [review]
Thanks @MohammadPCh

**Pull request merged**
