### PR TITLE
Allow clicks on menu items on verification page

### LINKED ISSUE #1982: Allow user to click next to see the other pages of the verification page
I was trying to demo the project verification to the World Food program and I couldn't get passed the verify the email step... I should be able to hit next and see what other requirements are needed without filling out every page of the form. 

Screen Shot 2022-12-27 at 11 17 43 PM

### PR DESCRIPTION
**Pull request by kkatusic**
Resolve #1982 

@RamRamez before we can test this I need to submit also PR to the backend and you need check that, thx

## Summary by CodeRabbit

- **New Features**
  - Added a warning icon for incomplete verification steps.
  - Enhanced Terms and Conditions component to handle new verification states and user actions.
  - Introduced new language support for indicating missing sections in Catalan, English, and Spanish.

- **Bug Fixes**
  - Adjusted verification step logic to ensure accurate step progression and clickability.

- **Improvements**
  - Updated dependency version for improved UI design.
  - Added new functions to improve the handling and checking of verification steps.
  - Refined the menu items structure to include specific slugs for better tracking.

- **Refactor**
  - Refactored verification context and helpers to streamline verification step determination.

### CODE REVIEW

**Review by RamRamez — APPROVED** [review]
Nice job, thanks @kkatusic 

I think you can remove warning icon from `social profiles` step, because that step is optional.

**Comment by kkatusic** [comment]
> Nice job, thanks @kkatusic
> 
> I think you can remove warning icon from `social profiles` step, because that step is optional.

In task they provided it, will I ask them or?

**Comment by RamRamez** [comment]
> > Nice job, thanks @kkatusic
> > I think you can remove warning icon from `social profiles` step, because that step is optional.
> 
> In task they provided it, will I ask them or?

@kkatusic It's up to you. This PR is approved. You can merge it and follow up with design team later.

**Comment by kkatusic** [comment]
> > > Nice job, thanks @kkatusic
> > > I think you can remove warning icon from `social profiles` step, because that step is optional.
> > 
> > 
> > In task they provided it, will I ask them or?
> 
> @kkatusic It's up to you. This PR is approved. You can merge it and follow up with design team after.

Thx @RamRamez for checking this and for all help ;)

**Pull request merged**
