### PR TITLE
ChainVine Frontend integration

### PR DESCRIPTION
**Pull request by mateodaza**

### CODE REVIEW

**Review by MohammadPCh — CHANGES_REQUESTED** [review]
Thanks @mateodaza ,
Do we really need nookies here?
because we shouldn't save user info on the server!
so we can easily use cookies here and don't adding  a new package to our project

**Comment by mateodaza** [comment]
Fixed! @MohammadPCh

**Review by MohammadPCh — APPROVED** [review]
LGTM, Thanks @mateodaza

**Comment by MohammadPCh** [comment]
@mateodaza we can merge it now :)
please resolve the conflict and merge.
Thank you for your great job.

**Pull request merged**
