### PR TITLE
Link onboarding guide in more places on the dapp

### PR DESCRIPTION
**Pull request by Meriem-BM**
Related to #3467

### CODE REVIEW

**Comment by Meriem-BM** [comment]
New added translation keys 

- label.learn_the_basics

- label.onboarding_guide

- label.learn_more_about_donating_on_giveth

- component.title.onboarding_guide

**Review by MohammadPCh — CHANGES_REQUESTED** [review]
@Meriem-BM Thanks for this great PR, Please use yarn instead.

**Comment by MohammadPCh** [comment]
> New added translation keys that need to. be translated:
> 
> * label.learn_the_basics
> * label.onboarding_guide
> * label.learn_more_about_donating_on_giveth
> * component.title.onboarding_guide

@Meriem-BM Thanks for mentioning, please use the ChatGPT for translation.

**Review by MohammadPCh — APPROVED** [review]
@Meriem-BM LGTM, Thanks.

**Pull request merged**
