### PR TITLE
Make Giveth dApp a Gnosis Safe App

### PR DESCRIPTION
**Pull request by mateodaza**

### CODE REVIEW

**Comment by mateodaza** [comment]
To test this out go to gnosis safe interface in apps section and go to Add Custom App

image

Then paste the deployment link, in our case is https://giveth-dapps-v2-h834l8zh3-givethio.vercel.app/
Later on people may be able to find it with the search bar

image

and that's it

**Review by aminlatifi — APPROVED** [review]

**Comment by aminlatifi** [comment]
LGTM. Thanks @mateodaza

**Comment by aminlatifi** [comment]
@mateodaza in case you infer the issue is related to givecnomy, please make PR to giveconomy branch

**Comment by mateodaza** [comment]
Thanks @aminlatifi !
Well this affects the whole app not only the giv economy side, as it relates more with authentication and signing. What do you prefer?

**Comment by aminlatifi** [comment]
> Thanks @aminlatifi ! Well this affects the whole app not only the giv economy side, as it relates more with authentication and signing. What do you prefer?

Oh, ok. I added it to Giveconomy too

**Pull request merged**
