### PR TITLE
Read subgraph Urls from .env (develop)

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
## Summary by CodeRabbit

- **New Features**
  - Introduced environment variable support for configuring subgraph URLs. This change enhances flexibility and allows dynamic endpoint configuration based on the environment.

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
@mhmdksh After merging this we should add these variables in Vercel for staging ENV
* **uniswapV2Subgraph**
* ** honeyswapV2Subgraph**
* **superFluidSubgraph**

**Review by RamRamez — APPROVED** [review]
Thanks @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@mhmdksh Feel free to merge it once you added the variables in Vercel panel

**Comment by mohammadranjbarz** [comment]
@mhmdksh 
* **NEXT_PUBLIC_SUBGRAPH_SUPER_FLUID**
* **NEXT_PUBLIC_SUBGRAPH_UNISWAP_V2**
* **NEXT_PUBLIC_SUBGRAPH_HONEYSWAP_V2**

**Comment by mhmdksh** [comment]
Thanks for updating the 

> @mhmdksh
> 
> * **NEXT_PUBLIC_SUBGRAPH_SUPER_FLUID**
> * **NEXT_PUBLIC_SUBGRAPH_UNISWAP_V2**
> * **NEXT_PUBLIC_SUBGRAPH_HONEYSWAP_V2**

Thanks for updating the ENV links @mohammadranjbarz 
I have added the ENV variables in our staging frontend, this is now safe to merge

**Review by RamRamez — APPROVED** [review]
Thanks @mohammadranjbarz

**Pull request merged**
