### PR TITLE
Fix/app global iframe

### PR DESCRIPTION
**Pull request by kkatusic**
- https://github.com/Giveth/giveth-dapps-v2/issues/4898

## Summary by CodeRabbit

- **New Features**
	- Added a redirect from `/comarketing` to download the Giveth Co-Marketing Slides PDF.
  
- **Security Enhancements**
	- Updated `X-Frame-Options` to allow framing from a specific origin.
	- Modified `Content-Security-Policy` to include the new origin in the frame-ancestors directive.
	- Added `Access-Control-Allow-Origin` header to enable CORS for the specified origin.

### CODE REVIEW

**Comment by kkatusic** [comment]
@divine-comedian when you find time you can check this preview link inside app.safe and if it ok, that is that ;)

**Comment by divine-comedian** [comment]
@kkatusic it's working! 

image

**Comment by kkatusic** [comment]
> @kkatusic it's working!
> 

excellent, need approve :)

**Review by RamRamez — APPROVED** [review]
Thanks @kkatusic

**Pull request merged**
