### PR TITLE
Hiding notification count and hover for notification bell

### PR DESCRIPTION
**Pull request by mateodaza**

### CODE REVIEW

**Review by CarlosQ96 — APPROVED** [review]

**Review by RamRamez — CHANGES_REQUESTED** [review]
@mateodaza I can still see the bell icon in the header. can you please check it?

**Review by RamRamez — CHANGES_REQUESTED** [review]
@mateodaza I think it's better to set an env variable to easily turn on and off the notification center.

**Comment by mateodaza** [comment]
> @mateodaza I can still see the bell icon in the header. can you please check it?

You can still see it, you won't check the count number or hover - the idea is to only allow user to see the notifications on the /notifications route

**Comment by mateodaza** [comment]
> @mateodaza I think it's better to set an env variable to easily turn on and off the notification center.

will add this :)

**Pull request merged**
