### PR TITLE
Fix verify button & tag

### PR DESCRIPTION
**Pull request by kkatusic**
- #4365 

@LatifatAbdullahi fixed project action dropdown menu when verify will show to user. Also added i18 label to verify project on single project page.

One combination was missing, when project verification form has been verified, but not verified project.

## Summary by CodeRabbit

- **New Features**
  - The `ProjectGIVbackToast` component now supports dynamic labeling for the verification button, enhancing internationalization and localization based on user language preferences.
  
- **Bug Fixes**
  - Addressed issues related to project verification status checks in the `ProjectActions` component, ensuring more accurate handling of verification forms.

### CODE REVIEW

**Comment by LatifatAbdullahi** [comment]
Noted

**Review by RamRamez — CHANGES_REQUESTED** [review]
@kkatusic I believe we should only rely on project.verified to check for verification status. Also in backend we only check that field.

I removed the fields causing this error in AdminJS. I think the FE logic is ok.

**Comment by kkatusic** [comment]
> @kkatusic I believe we should only rely on project.verified to check for verification status. Also in backend we only check that field.
> 
> I removed the fields causing this error in AdminJS. I think the FE logic is ok.

Thx @RamRamez, I need this PR because I missed condition where it checks if verification form data either exist: https://github.com/Giveth/giveth-dapps-v2/pull/4372/commits/1dae5a9dc8b4c11246b6c5576d5a1dc653dda1af

**Comment by RamRamez** [comment]
> Thx @RamRamez, I need this PR because I missed condition where it checks if verification form data either exist: [1dae5a9](https://github.com/Giveth/giveth-dapps-v2/commit/1dae5a9dc8b4c11246b6c5576d5a1dc653dda1af)

@kkatusic The issue #4365 is tested and verified, so I think you can revert [this commit](https://github.com/Giveth/giveth-dapps-v2/pull/4372/commits/003742ed80ce8f86cd5e1ae080597e2cae1dddaa) and keep the rest.

**Comment by kkatusic** [comment]
> > Thx @RamRamez, I need this PR because I missed condition where it checks if verification form data either exist: [1dae5a9](https://github.com/Giveth/giveth-dapps-v2/commit/1dae5a9dc8b4c11246b6c5576d5a1dc653dda1af)
> 
> @kkatusic The issue #4365 is tested and verified, so I think you can revert [this commit](https://github.com/Giveth/giveth-dapps-v2/pull/4372/commits/003742ed80ce8f86cd5e1ae080597e2cae1dddaa) and keep the rest.

Thx @RamRamez , but like I said before, we need this condition:

`(!project.verified && project.projectVerificationForm === null)`

from last commit

**Comment by RamRamez** [comment]
> > > Thx @RamRamez, I need this PR because I missed condition where it checks if verification form data either exist: [1dae5a9](https://github.com/Giveth/giveth-dapps-v2/commit/1dae5a9dc8b4c11246b6c5576d5a1dc653dda1af)
> > 
> > 
> > @kkatusic The issue #4365 is tested and verified, so I think you can revert [this commit](https://github.com/Giveth/giveth-dapps-v2/pull/4372/commits/003742ed80ce8f86cd5e1ae080597e2cae1dddaa) and keep the rest.
> 
> Thx @RamRamez , but like I said before, we need this condition:
> 
> `(!project.verified && project.projectVerificationForm === null)`
> 
> from last commit

@kkatusic Yes, I know. You can keep that one and just revert below commit.
https://github.com/Giveth/giveth-dapps-v2/pull/4372/commits/003742ed80ce8f86cd5e1ae080597e2cae1dddaa

**Comment by kkatusic** [comment]
Thx @RamRamez , reverted ;)

**Review by RamRamez — APPROVED** [review]
Thanks @kkatusic

**Review by MohammadPCh — APPROVED** [review]
Thanks @kkatusic

**Comment by MohammadPCh** [comment]
@kkatusic could you please resolve the conflict? then we can merge it.

**Pull request merged**
