### PR TITLE
Feat/752 project registry

### PR DESCRIPTION
**Pull request by alireza-sharifpour**
#752

### CODE REVIEW

**Review by RamRamez — CHANGES_REQUESTED** [review]
Great, thanks @alireza-sharifpour

**Comment by RamRamez** [comment]
focus border color should be giv[500]
I think it's better to set the width of drop-down menu equal to select component
also please check the drop-down menu hover color with the design system

image

**Comment by RamRamez** [comment]
Please also update the border color of the description input component

**Comment by alireza-sharifpour** [comment]
Thanks @RamRamez For review, I updated styles according to your feedback, please check it again

**Review by RamRamez — APPROVED** [review]

**Pull request merged**
