### PR TITLE
Feat/issue 4216

### PR DESCRIPTION
**Pull request by Reshzera**
## Summary by CodeRabbit

- **New Features**
  - Added support for GitHub social media links in project creation and editing.
  - Introduced GitHub icon and validation for social media inputs.

- **Improvements**
  - Enhanced data fetching in the `EditIndex` component to use a no-cache policy for more up-to-date information.

- **Bug Fixes**
  - Improved URL validation for GitHub links to ensure correct input format.

### CODE REVIEW

**Review by kkatusic — CHANGES_REQUESTED** [review]
@Reshzera checked code, looks good to me. Also I have tried vercel preview link, validation is working ok, but if I want to create project I'm getting error:
Screenshot 2024-07-18 at 00 08 06

Please check with @RamRamez must there be also changes on the backend side related to the github option value.

**Review by RamRamez — APPROVED** [review]
Great work, thanks @Reshzera

**Comment by RamRamez** [comment]
@kkatusic The backend PR is now merged on staging and you can test it.

**Comment by kkatusic** [comment]
> @kkatusic The backend PR is now merged on staging and you can test it.

Thx @RamRamez , now is everything ok.

**Review by kkatusic — APPROVED** [review]
thx @Reshzera

**Comment by Reshzera** [comment]
#4216

**Pull request merged**
