### PR TITLE
1539 add segment script

### PR DESCRIPTION
**Pull request by alireza-sharifpour**
- #1539

### CODE REVIEW

**Review by MohammadPCh — APPROVED** [review]
LGTM, Thanks @alireza-sharifpour

**Comment by MohammadPCh** [comment]
@alireza-sharifpour I don't merge it, and wait for the @ahmadabugosh decision for using it on development or not.

**Comment by ahmadabugosh** [comment]
hey @MohammadPCh We only need it in production (not development or staging), so you can disable those on Segment.

**Comment by MohammadPCh** [comment]
@ahmadabugosh
We just have to be aware that removing this part of the staging will disrupt the software production pipeline. Therefore, testing events must be done manually. (after every change and release)

**Pull request merged**
