### PR TITLE
Fix donation logic for one time donations

### PR DESCRIPTION
**Pull request by RamRamez**
#3488

### CODE REVIEW

**Comment by MohammadPCh** [comment]
@RamRamez @jainkrati We made changes to some of these parts in the recurring donation section, so I believe it's better to address this after the pull request is merged because some of these changes are compromising the functionality of that part.

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @RamRamez  LGTM

**Comment by RamRamez** [comment]
Ok, so I won't merge this PR now and will wait for recurring donations.

**Comment by RamRamez** [comment]
Recurring donations is merged and we can merge this now. @MohammadPCh can you review this please?

**Comment by MohammadPCh** [comment]
@RamRamez to fix the conflict, then I can review it. Thanks.

**Comment by RamRamez** [comment]
> @RamRamez to fix the conflict, then I can review it. Thanks.

Done!

**Review by MohammadPCh — APPROVED** [review]
Thanks @RamRamez

**Pull request merged**
