### PR TITLE
Mobile resp giveconomy

### PR DESCRIPTION
**Pull request by divine-comedian**
fixes to mobile responsiveness

### CODE REVIEW

**Comment by divine-comedian** [comment]
related to issue #345

**Comment by MohammadPCh** [comment]
Thank you @divine-comedian 
I think it's better to follow mobile-first rules in our CSS. `min width`
also please use mediaQueries instead of this pattern: `@media (max-width: ${deviceSize.mobileL}px) {`
for example you can DaoCardButton from this:
```
export const DaoCardButton = styled(ButtonLink)`
	width: 300px;
	margin-top: 36px;
	margin-bottom: 12px;
	@media (max-width: ${deviceSize.mobileL}px) {
		display: block;
		margin-left: auto;
		width: 136px;
	}
`;
```
to this:
```
export const DaoCardButton = styled(ButtonLink)`
	text-align: center;
	display: block;
	margin-left: auto;
	width: 136px;
	margin-top: 36px;
	margin-bottom: 12px;
	${mediaQueries.tablet} {
		margin-left: 0;
		width: 300px;
	}
`;
```

**Review by MohammadPCh — CHANGES_REQUESTED** [review]
Thank you @divine-comedian 
I think it's better to follow mobile-first rules in our CSS. `min width`
also please use mediaQueries instead of this pattern: `@media (max-width: ${deviceSize.mobileL}px) {`
for example you can DaoCardButton from this:
```
export const DaoCardButton = styled(ButtonLink)`
	width: 300px;
	margin-top: 36px;
	margin-bottom: 12px;
	@media (max-width: ${deviceSize.mobileL}px) {
		display: block;
		margin-left: auto;
		width: 136px;
	}
`;
```
to this:
```
export const DaoCardButton = styled(ButtonLink)`
	text-align: center;
	display: block;
	margin-left: auto;
	width: 136px;
	margin-top: 36px;
	margin-bottom: 12px;
	${mediaQueries.tablet} {
		margin-left: 0;
		width: 300px;
	}
`;
```

**Review by MohammadPCh — APPROVED** [review]
LGTM, Thank you @divine-comedian

**Pull request merged**
