### PR TITLE
Adding hotfix for wallet connect modal

### LINKED ISSUE #4109: WalletConect widget popping out repeatedly
I signed in with my Metamask and got this behaviour immediately: https://cln.sh/r5P290nR

### PR DESCRIPTION
**Pull request by kkatusic**
Fix #4109 , it is hotfix to hide additional wallet connect modal that is showing.

@MohammadPCh check this

## Summary by CodeRabbit

- **Style**
  - Updated modal display settings to enhance user interface experience.

### CODE REVIEW

**Comment by maryjaf** [comment]
I've checked on this branch and the problem of WalletConect widget popping out repeatedly doesn't happen again to me, 
but I couldn't sign in by wallet connect option 
could someone else check it with his device to be sure it works or not ?
 @kkatusic @MohammadPCh 

My device: iphone 12
Desktop browser: chrome

**Comment by kkatusic** [comment]
> I've checked on this branch and the problem of WalletConect widget popping out repeatedly doesn't happen again to me, but I couldn't sign in by wallet connect option could someone else check it with his device to be sure it works or not ? @kkatusic @MohammadPCh
> 
> My device: iphone 12 Desktop browser: chrome

What wallet you used? Can you test same on stagging?

**Comment by maryjaf** [comment]
> > I've checked on this branch and the problem of WalletConect widget popping out repeatedly doesn't happen again to me, but I couldn't sign in by wallet connect option could someone else check it with his device to be sure it works or not ? @kkatusic @MohammadPCh
> > My device: iphone 12 Desktop browser: chrome
> 
> What wallet you used? Can you test same on stagging?

I had checked with metamask yesterday.
maybe the problem was related to my connection because today I could sign with wallet connect->metamask 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/eccca9e8-c60e-40ab-92b1-e5d279ad4476

**Comment by kkatusic** [comment]
> > > I've checked on this branch and the problem of WalletConect widget popping out repeatedly doesn't happen again to me, but I couldn't sign in by wallet connect option could someone else check it with his device to be sure it works or not ? @kkatusic @MohammadPCh
> > > My device: iphone 12 Desktop browser: chrome
> > 
> > 
> > What wallet you used? Can you test same on stagging?
> 
> I had checked with metamask yesterday. maybe the problem was related to my connection because today I could sign with wallet connect->metamask
> Screen.Recording.2024-06-19.at.9.56.33.AM.mov

Can you please check in incognito mode and also in another browser? thx @maryjaf

**Comment by maryjaf** [comment]
> I had checked with metamask yesterday.
> maybe the problem was related to my connection because today I could sign with wallet connect->metamask

I had also checked on incognito mode and firefox and it worked correctly

**Review by MohammadPCh — APPROVED** [review]
@kkatusic It's ok as temporary fix, but we need to find the root cause

**Pull request merged**
