### PR TITLE
add dai token image to staking card

### PR DESCRIPTION
**Pull request by divine-comedian**
add dai token image to staking card

### CODE REVIEW

**Comment by aminlatifi** [comment]
@divine-comedian We implement icons in ui-system-design project.

**Comment by aminlatifi** [comment]
@divine-comedian it's working, thanks

**Review by MohammadPCh — APPROVED** [review]
Nice, Thank you @divine-comedian

**Comment by MohammadPCh** [comment]
> @divine-comedian We implement icons in ui-system-design project.

I suggest moving all of our currency icons to the design system project in another PR.

**Pull request merged**
