### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by MohammadPCh**

### CODE REVIEW

**Comment by MohammadPCh** [comment]
@jainkrati, Okay, we're ready to test this branch. I highly recommend testing it before merging it into the staging environment because it includes numerous changes and there may be breaking changes. What are your thoughts?

**Comment by jainkrati** [comment]
> @jainkrati, Okay, we're ready to test this branch. I highly recommend testing it before merging it into the staging environment because it includes numerous changes and there may be breaking changes. What are your thoughts?

Yes we should test it before merging. @maryjaf could you test this branch tomorrow for a full sanity of the app? Once done, @MohammadPCh can merge

**Comment by maryjaf** [comment]
- [ ] 1-

image

- [ ] 2-

image

- [ ] 3-

image

- [ ] 4-

image

- [ ] 5-available balance  isn't shown like as stg
image
image

- [ ] 6-

image
image

- [ ] 7-I couldn't complete a success  donation flow but i'm not sure it's relate o these changes or not 

image

- [ ] 8-
image


- [ ] 9-
image

- [ ] 10-
image

**Comment by maryjaf** [comment]
- [ ] 10- Multisig account doesn't work correctly on this branch 
In below video I try to show the behavior on this branch and stg 


https://github.com/Giveth/giveth-dapps-v2/assets/111529185/652356a2-5e29-4e1e-ba9f-9b6fd40ab214

**Comment by MohammadPCh** [comment]
@maryjaf Could you please test them again? Thanks.

**Comment by maryjaf** [comment]
Item 6: style of modal hasn't been fixed 
image

**Comment by maryjaf** [comment]
> @maryjaf Could you please test them again? Thanks.

I've checked some of these problems but it seem these haven't been fixed 
for example 1,2 & 6
Please let me know to test again when all of them would be fixed 
or tell me which of them have been resolved.
image

image

**Comment by MohammadPCh** [comment]
@maryjaf Thanks, Are you sure? because all of them are fixed for me. let's have a call and check together.

**Comment by MohammadPCh** [comment]
> Thanks @MohammadPCh all problems have been resolved on https://giveth-dapps-v2-git-update-packages-givethio.vercel.app/qf/all

@jainkrati can we merge it now?

**Review by jainkrati — APPROVED** [review]

**Review by alireza-sharifpour — APPROVED** [review]
Thanks @MohammadPCh

**Pull request merged**
