### PR TITLE
Fix errors

### PR DESCRIPTION
**Pull request by MohammadPCh**
- #3528

### CODE REVIEW

**Review by aminlatifi — APPROVED** [review]
LGTM, thanks @MohammadPCh

**Comment by aminlatifi** [comment]
@MohammadPCh Would you please apply similar changes to the production env?

**Comment by MohammadPCh** [comment]
@aminlatifi, considering that we are planning to release today, perhaps it is acceptable to include it in this release.

**Comment by aminlatifi** [comment]
Okay
So let's merge this one

**Pull request merged**
