### PR TITLE
GIVclaim redesign to show the drop has ended

### PR DESCRIPTION
**Pull request by mateodaza**

### CODE REVIEW

**Review by MohammadPCh — COMMENTED** [review]
LGTM, Thanks @mateodaza

**Review by MohammadPCh — APPROVED** [review]

**Comment by MohammadPCh** [comment]
@laurenluz Are We gonna have a hotfix for it?

**Comment by laurenluz** [comment]
yeah I think that would be nice!

there is no huge hurry, but it would be nice to not have to think about the GIVdrop ever again 😅

**Comment by MohammadPCh** [comment]
@mateodaza could you please change it to main?

**Pull request closed without merging**
