### PR TITLE
feature: spanish version with i18n 

### PR DESCRIPTION
**Pull request by mateodaza**

### CODE REVIEW

**Comment by maryjaf** [comment]
image

**Comment by mateodaza** [comment]
Excellent feedback @maryjaf ! I’m meeting with the team soon and this helps a lot. About #3 and #7 that’s Spanish grammar, about #4 it’s not related to translations

**Comment by maryjaf** [comment]
> Excellent feedback @maryjaf ! I’m meeting with the team soon and this helps a lot. About #3 and #7 that’s Spanish grammar, about #4 it’s not related to translations

Thanks @mateodaza 
# 7 isn't happened on English version , it's weird

**Review by MohammadPCh — APPROVED** [review]
@mateodaza  LGTM, thanks.

**Pull request merged**
