### PR TITLE
Add to NavBar Charts External link

### PR DESCRIPTION
**Pull request by luizakp**
Add desktop and mobile version to access giveth info external charts through navbar

### CODE REVIEW

**Comment by mendesfabio** [comment]
Not sure who's been reviewing PRs for Giveth, so tagging you both @mateodaza @MohammadPCh. For context, see https://forum.giveth.io/t/giveth-info-an-analytics-tool-for-the-community/514/28.

**Comment by MoeNick** [comment]
We need to QA the accuracy of the data first before making it live.

**Comment by MoeNick** [comment]
@Cotabe can take a look and QAimg with @WhyldWanderer .

**Comment by MohammadPCh** [comment]
Thanks @luizapuccinelli and @mendesfabio 
I think we need @mosaeedi confirmation for merging it.
It seems that this PR is not based on the giveth design system.

**Comment by mateodaza** [comment]
@mosaeedi @MohammadPCh pinging you again on this

**Comment by MoeNick** [comment]
I think we need to close this? @MohammadPCh

**Pull request closed without merging**
