### PR TITLE
Support Giveth Subgraphs as ENV Variables

### PR DESCRIPTION
**Pull request by RamRamez**
#4223

## Summary by CodeRabbit

- **Chores**
  - Updated subgraph addresses to use environment variables for enhanced configurability and flexibility across different chains (mainnet, xDai, Optimism, Ethereum Classic).

### CODE REVIEW

**Comment by mhmdksh** [comment]
@RamRamez Can you please follow the suggestions by coderabbit.

We should put a default value, if we removed the values that are in place now. Since if there was no default value (Or for any reason we didn't configure it, as is the case in the current setup), the frontend might not start.

**Review by kkatusic — APPROVED** [review]
Yes, LGTM ;)

**Comment by mhmdksh** [comment]
> Yes, LGTM ;)

@kkatusic If this is merged as it is now, the frontend might not start with the current config

**Comment by RamRamez** [comment]
> @RamRamez Can you please follow the suggestions by coderabbit.
> 
> We should put a default value, if we removed the values that are in place now. Since if there was no default value (Or for any reason we didn't configure it, as is the case in the current setup), the frontend might not start.

Done!

**Review by mhmdksh — APPROVED** [review]
These look good now, Thanks @RamRamez great work :)

**Comment by RamRamez** [comment]
> These look good now, Thanks @RamRamez great work :)

But coderabbit is not convinced yet :))

**Pull request merged**
