### PR TITLE
WIP: Improve back option

### PR DESCRIPTION
**Pull request by kkatusic**
- #3417

## Summary by CodeRabbit

- **New Features**
  - Introduced a unique ID property for the CardBody component to enhance accessibility and styling.
  - Implemented an infinite scrolling feature in the ProjectsIndex for dynamic loading of project data.
  - Added support for connecting with the Safe wallet, enhancing wallet connectivity options.

- **Improvements**
  - Enhanced pagination handling and loading state management through the use of React Query's `useInfiniteQuery` hook.
  - Improved responsiveness of the ProjectGIVbackToast component for better layout on larger screens.

- **Bug Fixes**
  - Streamlined UI updates during data fetching by leveraging built-in flags for better user experience.
  - Adjusted tab activation logic in the DonationCard component for Endaoment projects to improve user experience.

### CODE REVIEW

**Comment by kkatusic** [comment]
@MohammadPCh just don't forget this :)

**Comment by alireza-sharifpour** [comment]
Thanks @kkatusic!
I checked it but I noticed something.

I filtered the QF projects but the number of total
Screenshot 2024-09-04 at 4 38 23 PM
 projects didn't change, can you take a look?

**Comment by kkatusic** [comment]
> Thanks @kkatusic! I checked it but I noticed something.
> 
> I filtered the QF projects but the number of total Screenshot 2024-09-04 at 4 38 23 PM projects didn't change, can you take a look?

Found some time again to check this, when you @alireza-sharifpour found time please can you review it again? thx

**Review by MohammadPCh — COMMENTED** [review]
@kkatusic Thanks, this is great! My suggestion would be to update the fetchProjects function to return the appropriate data in a way that allows the returned object to be used as state. That way, we won’t need to set separate states like setTotalPages, setTotalCount, and setFilteredProjects. Once that's done, we could move this function to the service file for better organization.

**Comment by kkatusic** [comment]
thx @MohammadPCh , changes have been made, please check again ;)

**Review by MohammadPCh — APPROVED** [review]
Thanks @kkatusic LGTM

**Pull request merged**
